import { beforeEach, describe, expect, it } from 'vitest'
import { useGameStore } from '../src/store/gameStore'
import { createGame } from '../src/game/state/initial'
import { isInCheck } from '../src/game/rules'
import type { Board, Piece, PieceType, Side } from '../src/types/game'

const piece = (type: PieceType, side: Side = 'red'): Piece => ({ id: `${side}-${type}`, type, side, name: type })
function emptyBoard(): Board { return Array.from({ length: 10 }, () => Array<Piece | null>(9).fill(null)) }

describe('State local', () => {
  beforeEach(() => useGameStore.getState().reset(0))
  it('khai cuộc 1,3 giây giữ đồng hồ và khóa chọn quân', () => {
    const store = useGameStore.getState()
    store.start(0)
    store.select({ row: 6, col: 0 }, 1299)
    expect(useGameStore.getState().selected).toBeNull()
    expect(useGameStore.getState().game.remainingTime.red).toBe(600000)
    store.select({ row: 6, col: 0 }, 1300)
    expect(useGameStore.getState().selected).toEqual({ row: 6, col: 0 })
    store.tick(1400)
    expect(useGameStore.getState().game.remainingTime.red).toBe(599900)
  })
  it('khóa trước sẵn sàng và trong animation; reset hủy nước đang chờ', () => {
    let state = useGameStore.getState()
    state.select({ row: 6, col: 0 }, 0)
    expect(useGameStore.getState().selected).toBeNull()
    state.start(-1300)
    state.select({ row: 6, col: 0 }, 0)
    state.select({ row: 5, col: 0 }, 0)
    state = useGameStore.getState()
    expect(state.animation).not.toBeNull()
    const version = state.animationVersion
    state.select({ row: 6, col: 2 }, 0)
    expect(useGameStore.getState().selected).toBeNull()
    state.reset(50)
    state.completeAnimation(version, 200)
    expect(useGameStore.getState().game.board[6][0]?.side).toBe('red')
    expect(useGameStore.getState().game.board[5][0]).toBeNull()
  })
  it('hoàn thành animation đúng một lần, không tính giờ animation', () => {
    const store = useGameStore.getState()
    store.start(-1300); store.select({ row: 6, col: 0 }, 100); store.select({ row: 5, col: 0 }, 100)
    const version = useGameStore.getState().animationVersion
    store.completeAnimation(version, 400)
    store.completeAnimation(version, 800)
    expect(useGameStore.getState().moves).toEqual(['a3a4'])
    expect(useGameStore.getState().game.currentTurn).toBe('black')
    expect(useGameStore.getState().game.remainingTime.red).toBe(599900)
  })
  it('đi lại local chỉ có sau nước đầu tiên và trừ tối đa hai lần', () => {
    let store = useGameStore.getState()
    store.start(-1300)
    expect(store.history).toHaveLength(0)
    store.select({ row: 6, col: 0 }, 500, false)
    store.select({ row: 5, col: 0 }, 500, false)
    store = useGameStore.getState()
    expect(store.history).toHaveLength(1)
    store.takeback(1, 100)
    expect(useGameStore.getState().game.board[6][0]?.side).toBe('red')
    expect(useGameStore.getState().moves).toEqual([])
    expect(useGameStore.getState().game.remainingTime.red).toBe(600000)
    expect(useGameStore.getState().takebacksRemaining).toBe(1)
    useGameStore.getState().takeback(1, 200)
    expect(useGameStore.getState().takebacksRemaining).toBe(1)
  })
  it('restores both clocks when taking back two plies', () => {
    let store = useGameStore.getState()
    store.start(-1300)
    store.select({ row: 6, col: 0 }, 500, false)
    store.select({ row: 5, col: 0 }, 500, false)
    store = useGameStore.getState()
    store.select({ row: 3, col: 0 }, 900, false)
    store.select({ row: 4, col: 0 }, 900, false)
    expect(useGameStore.getState().game.remainingTime).toEqual({ red: 599500, black: 599600 })
    useGameStore.getState().takeback(2, 1000, false)
    expect(useGameStore.getState().game.remainingTime).toEqual({ red: 600000, black: 600000 })
  })
  it('hòa, xin thua và timeout khóa ván', () => {
    const store = useGameStore.getState()
    store.start(-1300); store.finish(true, 100)
    expect(useGameStore.getState().game.result).toEqual({ winner: null, reason: 'draw' })
    store.reset(0); store.start(-1300); store.finish(false, 100)
    expect(useGameStore.getState().game.result).toEqual({ winner: 'black', reason: 'resign' })
    store.reset(0); store.start(-1300); store.finish(true, 600000)
    expect(useGameStore.getState().game.result?.reason).toBe('timeout')
  })
  it('đi qua store vẫn nhận nước chiếu và kết thúc đúng khi chiếu bí', () => {
    const board = emptyBoard()
    board[0][4] = piece('general', 'black')
    board[9][4] = piece('general')
    board[2][4] = piece('rook')
    useGameStore.setState({ game: { ...createGame(0), board, phase: 'playing' } })
    let store = useGameStore.getState()
    store.select({ row: 2, col: 4 }, 0, false)
    store.select({ row: 1, col: 4 }, 0, false)
    let game = useGameStore.getState().game
    expect(isInCheck('black', game.board)).toBe(true)
    expect(game.phase).toBe('playing')
    expect(game.result).toBeNull()

    const mateBoard = emptyBoard()
    mateBoard[0][4] = piece('general', 'black')
    mateBoard[9][4] = piece('general')
    mateBoard[1][3] = piece('rook')
    mateBoard[1][5] = piece('rook')
    mateBoard[2][4] = piece('rook')
    useGameStore.setState({ game: { ...createGame(0), board: mateBoard, phase: 'playing' }, selected: { row: 2, col: 4 } })
    store = useGameStore.getState()
    store.select({ row: 1, col: 4 }, 0, false)
    game = useGameStore.getState().game
    expect(game.result).toEqual({ winner: 'red', reason: 'checkmate' })
    expect(game.phase).toBe('finished')
    const finalBoard = game.board
    useGameStore.getState().select({ row: 1, col: 3 }, 0, false)
    expect(useGameStore.getState().game.board).toBe(finalBoard)
  })
  it('đi thường, ăn quân, undo và replay bằng state ban đầu', () => {
    let store = useGameStore.getState()
    store.start(-1300)
    store.select({ row: 6, col: 0 }, 0, false)
    store.select({ row: 5, col: 0 }, 0, false)
    store.select({ row: 3, col: 0 }, 0, false)
    store.select({ row: 4, col: 0 }, 0, false)
    store.select({ row: 5, col: 0 }, 0, false)
    store.select({ row: 4, col: 0 }, 0, false)
    expect(useGameStore.getState().game.board.flat().filter(Boolean)).toHaveLength(31)
    expect(useGameStore.getState().history).toHaveLength(3)

    useGameStore.getState().takeback(2, 0, false)
    expect(useGameStore.getState().history).toHaveLength(1)
    expect(useGameStore.getState().game.board.flat().filter(Boolean)).toHaveLength(32)

    useGameStore.getState().finish(true, 0)
    useGameStore.getState().reset(100)
    useGameStore.getState().start(100)
    store = useGameStore.getState()
    expect(store.game.phase).toBe('playing')
    expect(store.game.result).toBeNull()
    expect(store.game.board.flat().filter(Boolean)).toHaveLength(32)
    expect(store.history).toEqual([])
    expect(store.moves).toEqual([])
    store.select({ row: 6, col: 0 }, 1400, false)
    store.select({ row: 5, col: 0 }, 1400, false)
    expect(useGameStore.getState().history).toHaveLength(1)
  })
})
