// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { App } from '../src/app/App'
import { useGameStore } from '../src/store/gameStore'
import { useSessionStore } from '../src/store/sessionStore'
import { roomApi } from '../src/services/api'
import { roomSocket } from '../src/services/socket'
import { pikafishApi } from '../src/services/pikafish'

beforeEach(() => {
  vi.stubGlobal('ResizeObserver', class { observe() {} disconnect() {} })
  window.matchMedia = vi.fn().mockImplementation(() => ({ matches: true, addEventListener() {}, removeEventListener() {} }))
  HTMLDialogElement.prototype.showModal = function () { this.open = true }
  HTMLDialogElement.prototype.close = function () { this.open = false }
  useGameStore.getState().reset(performance.now())
  useSessionStore.setState({ screen: 'game', mode: 'local', computerEngine: 'basic', humanSide: 'red', lobbyOpen: false, room: null, name: 'Picolozz', notice: '', messages: [] })
})
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); vi.unstubAllGlobals() })
function mount() {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  render(<QueryClientProvider client={client}><App /></QueryClientProvider>)
  return client
}
describe('React regression', () => {
  it('keeps chat expandable when the red player is in the right column after a game starts', () => {
    vi.useFakeTimers()
    useSessionStore.setState({ mode: 'computer', humanSide: 'black' })
    mount()

    const redCard = document.getElementById('player-red')!
    const chatPanel = document.getElementById('chatForm')!.parentElement!
    const toggle = document.getElementById('chatToggle')!
    expect(redCard).toHaveClass('flex-none')
    expect(redCard).not.toHaveClass('h-full')

    fireEvent.click(toggle)
    expect(toggle).toHaveAttribute('aria-expanded', 'true')
    const expandedClass = chatPanel.className

    act(() => useGameStore.getState().start(performance.now()))

    expect(document.getElementById('chatToggle')).toBe(toggle)
    expect(toggle).toHaveAttribute('aria-expanded', 'true')
    expect(chatPanel.className).toBe(expandedClass)
    fireEvent.click(toggle)
    expect(toggle).toHaveAttribute('aria-expanded', 'false')
    fireEvent.click(toggle)
    expect(toggle).toHaveAttribute('aria-expanded', 'true')
  })
  it('mở một danh sách người xem với ba thẻ tên dài ngắn khác nhau', () => {
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Người trong phòng' }))
    const panel = screen.getByRole('region', { name: 'Danh sách người xem' })
    expect(panel).toHaveClass('size-full', 'bg-[#061e2280]')
    expect(within(panel).getByText('Picolozz')).toBeInTheDocument()
    expect(within(panel).getByText('An')).toBeInTheDocument()
    expect(within(panel).getByText('Nguyễn Hoàng Minh Khôi')).toBeInTheDocument()
    expect(within(panel).getByRole('img', { name: 'Đang chờ đấu' }).closest('li')).toHaveTextContent('An')
    expect(within(panel).getAllByRole('listitem')[0]).toHaveTextContent('An')
  })
  it('mở Chơi với máy, chọn đen và bắt đầu ván Pikafish', async () => {
    vi.spyOn(pikafishApi, 'ready').mockResolvedValue()
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chơi Với Máy' }))
    expect(screen.getByRole('main', { name: 'Chơi với máy' })).toBeInTheDocument()
    expect(screen.getByRole('combobox', { name: 'Máy bên đen' })).toHaveValue('pikafish')
    fireEvent.click(screen.getByRole('radio', { name: 'Đen' }))
    expect(screen.getByRole('radio', { name: 'Đen' })).toBeChecked()
    fireEvent.click(screen.getByRole('button', { name: 'Đấu ngay' }))
    expect(await screen.findByRole('heading', { name: 'Pikafish' })).toBeInTheDocument()
    expect(useSessionStore.getState()).toMatchObject({ screen: 'game', mode: 'computer', humanSide: 'black', computerEngine: 'pikafish' })
    fireEvent.click(screen.getByRole('button', { name: 'Rời phòng' }))
    expect(screen.getByRole('main', { name: 'Màn hình chính' })).toBeInTheDocument()
  })
  it('báo lỗi kết nối Pikafish và giữ màn hình chọn máy', async () => {
    vi.spyOn(pikafishApi, 'ready').mockRejectedValue(new Error('Pikafish chưa sẵn sàng'))
    useSessionStore.setState({ screen: 'computer' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Đấu ngay' }))
    expect(await screen.findByRole('dialog', { name: 'Thông báo' })).toHaveTextContent('Pikafish chưa sẵn sàng')
    expect(useSessionStore.getState().screen).toBe('computer')
  })
  it('Chơi với máy giữ Home phía sau và mở lại hiệu ứng 600ms', () => {
    vi.useFakeTimers()
    window.matchMedia = vi.fn().mockImplementation(() => ({ matches: false, addEventListener() {}, removeEventListener() {} }))
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chơi Với Máy' }))
    expect(screen.getByTestId('computer-entrance')).toHaveAttribute('data-entering', 'true')
    expect(screen.getByRole('main', { name: 'Màn hình chính', hidden: true }).parentElement).toHaveAttribute('inert')
    act(() => vi.advanceTimersByTime(600))
    expect(screen.getByTestId('computer-entrance')).toHaveAttribute('data-entering', 'false')
    expect(screen.queryByRole('main', { name: 'Màn hình chính' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Về trang chủ' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chơi Với Máy' }))
    expect(screen.getByTestId('computer-entrance')).toHaveAttribute('data-entering', 'true')
  })
  it('Home mở Cờ Úp, giấu 30 mặt quân, lật sau nước đi và trở lại Cờ Tướng', () => {
    vi.useFakeTimers()
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Cờ Úp' }))
    expect(screen.getByRole('main', { name: 'Cờ Úp' })).toBeInTheDocument()
    expect(screen.getAllByTestId('covered-piece')).toHaveLength(30)
    expect(screen.getAllByRole('button', { name: /Quân úp/ })).toHaveLength(30)
    fireEvent.click(screen.getByRole('button', { name: 'Sẵn sàng' }))
    act(() => vi.advanceTimersByTime(1300))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 7, cột 1, Quân úp' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1' }))
    expect(screen.getAllByTestId('covered-piece')).toHaveLength(29)
    act(() => vi.advanceTimersByTime(600))
    expect(screen.getAllByTestId('covered-piece').length).toBeLessThanOrEqual(28)
    fireEvent.click(screen.getByRole('button', { name: 'Rời phòng' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chơi hai người cùng máy' }))
    expect(screen.queryAllByTestId('covered-piece')).toHaveLength(0)
    expect(screen.getByRole('main', { name: 'Cờ Tướng' })).toBeInTheDocument()
  })
  it('Chơi Nhanh vào thẳng bàn có người chờ, không mở trang Chọn Bàn', async () => {
    vi.spyOn(roomApi, 'list').mockResolvedValue([
      { id: 'full', name: 'Đủ', players: 2, phase: 'playing' },
      { id: 'empty', name: 'Rỗng', players: 0, phase: 'ready' },
      { id: 'waiting', name: 'Chờ', players: 1, phase: 'ready' },
    ])
    const join = vi.spyOn(roomSocket, 'join').mockResolvedValue({
      id: 'waiting', name: 'Chờ', players: [], game: useGameStore.getState().game, messages: [], drawOffer: null,
    })
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chơi Nhanh' }))
    await screen.findByRole('button', { name: 'Rời phòng' })
    expect(join).toHaveBeenCalledExactlyOnceWith('waiting', 'Picolozz')
    expect(useSessionStore.getState().screen).toBe('game')
    expect(screen.queryByRole('main', { name: 'Chọn Bàn' })).not.toBeInTheDocument()
  })
  it('Chơi Nhanh mở bàn với máy khi hết bàn online', async () => {
    vi.spyOn(roomApi, 'list').mockResolvedValue([])
    const join = vi.spyOn(roomSocket, 'join')
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chơi Nhanh' }))
    expect(await screen.findByRole('heading', { name: 'Máy · Cơ bản' })).toBeInTheDocument()
    expect(join).not.toHaveBeenCalled()
    expect(useSessionStore.getState().screen).toBe('game')
    expect(useSessionStore.getState().mode).toBe('computer')
  })
  it('máy đáp nước, người chơi không điều khiển đen và rời bàn hủy lượt máy', () => {
    vi.useFakeTimers()
    useSessionStore.setState({ screen: 'game', mode: 'computer' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Sẵn sàng' }))
    act(() => vi.advanceTimersByTime(1300))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 7, cột 1, 兵' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1' }))
    expect(useGameStore.getState().game.currentTurn).toBe('black')
    expect(screen.getByRole('button', { name: 'Hàng 4, cột 1, 卒' })).toBeDisabled()
    act(() => vi.advanceTimersByTime(600))
    expect(useGameStore.getState().game.currentTurn).toBe('red')
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1, 兵' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 5, cột 1' }))
    fireEvent.click(screen.getByRole('button', { name: 'Rời phòng' }))
    act(() => vi.advanceTimersByTime(1000))
    expect(useGameStore.getState().game.phase).toBe('ready')
    expect(useGameStore.getState().game.lastMove).toBeNull()
  })
  it('Chọn Bàn hiển thị phòng thật, lọc bàn trống và mở form tạo bàn', async () => {
    vi.spyOn(roomApi, 'list').mockResolvedValue([
      { id: 'open', name: 'Bàn trống', players: 1, phase: 'ready' },
      { id: 'full', name: 'Bàn đủ', players: 2, phase: 'playing' },
    ])
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chọn Bàn' }))
    const dialog = screen.getByRole('main', { name: 'Chọn Bàn' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.queryByRole('main', { name: 'Màn hình chính' })).not.toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Chọn thời gian' }))
    expect(within(dialog).getAllByRole('option')).toHaveLength(5)
    fireEvent.change(within(dialog).getByRole('combobox', { name: 'Thời gian ván' }), { target: { value: '5' } })
    expect(within(dialog).getByRole('button', { name: 'Chơi nhanh 5 phút' })).toBeInTheDocument()
    expect(await within(dialog).findByRole('button', { name: 'Vào phòng Bàn đủ, 2/2 người' })).toBeDisabled()
    expect(within(dialog).getByRole('button', { name: 'Vào phòng Bàn trống, 1/2 người' })).toBeEnabled()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Còn trống' }))
    expect(within(dialog).queryByRole('button', { name: 'Vào phòng Bàn đủ, 2/2 người' })).not.toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Tạo bàn' }))
    expect(within(dialog).getByRole('form', { name: 'Tạo bàn mới' })).toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: 'Hủy' }))
    expect(within(dialog).queryByRole('form')).not.toBeInTheDocument()
  })
  it('Chọn Bàn mở từ tâm trong 600ms và chạy lại khi mở lần nữa', () => {
    vi.useFakeTimers()
    vi.spyOn(roomApi, 'list').mockResolvedValue([])
    window.matchMedia = vi.fn().mockImplementation(query => ({ matches: !query.includes('prefers-reduced-motion'), addEventListener() {}, removeEventListener() {} }))
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chọn Bàn' }))
    expect(screen.getByTestId('lobby-entrance')).toHaveAttribute('inert')
    act(() => vi.advanceTimersByTime(600))
    expect(screen.getByTestId('lobby-entrance')).not.toHaveAttribute('inert')
    fireEvent.click(screen.getByRole('button', { name: 'Đóng' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chọn Bàn' }))
    expect(screen.getByTestId('lobby-entrance')).toHaveAttribute('data-entering', 'true')
  })
  it('giữ Home phía sau trong lúc mở phòng rồi gỡ sau 0,6 giây', () => {
    vi.useFakeTimers()
    window.matchMedia = vi.fn().mockImplementation(query => ({ matches: !query.includes('prefers-reduced-motion'), addEventListener() {}, removeEventListener() {} }))
    useSessionStore.setState({ screen: 'home' })
    mount()
    const home = screen.getByRole('main', { name: 'Màn hình chính' })
    fireEvent.click(screen.getByRole('button', { name: 'Chơi hai người cùng máy' }))
    expect(home).toBeInTheDocument()
    expect(home.parentElement).toHaveAttribute('inert')
    act(() => vi.advanceTimersByTime(599))
    expect(home).toBeInTheDocument()
    act(() => vi.advanceTimersByTime(1))
    expect(home).not.toBeInTheDocument()
    expect(screen.getByTestId('room-entrance')).toHaveAttribute('data-entering', 'false')
  })
  it('avatar mở hồ sơ, hiển thị hai quân cờ và đóng để trở lại home', () => {
    useSessionStore.setState({ screen: 'home' })
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Hồ sơ và tên người chơi' }))
    const profile = screen.getByRole('dialog', { name: 'Thông tin' })
    expect(within(profile).getByRole('heading', { name: 'Picolozz' })).toBeInTheDocument()
    expect(within(profile).getByRole('img', { name: 'Quân Tướng đỏ' })).toBeInTheDocument()
    expect(within(profile).getByRole('img', { name: 'Quân cờ úp' })).toBeInTheDocument()
    expect(within(profile).getByText('Lượt thích:', { exact: false })).toBeInTheDocument()
    expect(within(profile).getByText('TP. Hồ Chí Minh')).toBeInTheDocument()
    expect(useSessionStore.getState().lobbyOpen).toBe(false)
    fireEvent.click(within(profile).getByRole('button', { name: 'Liên kết tài khoản' }))
    expect(screen.getByRole('dialog', { name: 'Thông báo' })).toHaveTextContent('Liên kết tài khoản sắp ra mắt')
    fireEvent.click(screen.getByRole('button', { name: 'Đã hiểu' }))
    fireEvent.click(within(profile).getByRole('button', { name: 'Thoát' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Hồ sơ và tên người chơi' }))
    expect(screen.getByRole('dialog', { name: 'Thông tin' })).toBeInTheDocument()
  })
  it('màn hình chính mở phòng, đóng dialog và vào bàn local', () => {
    useSessionStore.setState({ screen: 'home' })
    mount()
    expect(screen.getByRole('heading', { name: 'Giải đấu' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Chọn Bàn' }))
    expect(screen.getByRole('main', { name: 'Chọn Bàn' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Đóng' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Chơi hai người cùng máy' }))
    expect(screen.getAllByTestId(/^piece-/)).toHaveLength(32)
  })
  it('hết khai cuộc đồng hồ đỏ tự chạy dù chưa chọn hay đi quân', () => {
    vi.useFakeTimers()
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Sẵn sàng' }))
    act(() => vi.advanceTimersByTime(1300))
    expect(screen.getByTestId('match-intro')).not.toBeVisible()
    expect(screen.getByLabelText('Thời gian quân đỏ')).toHaveTextContent('10:00')
    expect(screen.getByLabelText('Thời gian quân đen')).toHaveTextContent('10:00')
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.getByLabelText('Thời gian quân đỏ')).toHaveTextContent('09:59')
    expect(screen.getByLabelText('Thời gian quân đen')).toHaveTextContent('10:00')
    act(() => vi.advanceTimersByTime(1000))
    expect(screen.getByLabelText('Thời gian quân đỏ')).toHaveTextContent('09:58')
  })
  it('sẵn sàng, chọn/đi/ăn quân, xin thua và rời bàn', () => {
    vi.useFakeTimers()
    mount()
    expect(screen.getAllByTestId(/^piece-/)).toHaveLength(32)
    expect(screen.getAllByTestId('board-hit')).toHaveLength(90)
    fireEvent.click(screen.getByRole('button', { name: 'Sẵn sàng' }))
    expect(screen.getByRole('button', { name: 'Hàng 7, cột 1, 兵' })).toBeDisabled()
    act(() => vi.advanceTimersByTime(1300))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 7, cột 1, 兵' }))
    expect(screen.getAllByTestId('move-marker')).toHaveLength(1)
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1' }))
    expect(screen.getByTestId('piece-5-0')).toHaveTextContent('兵')
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 4, cột 1, 卒' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 5, cột 1' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1, 兵' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 5, cột 1, 卒' }))
    expect(screen.getAllByTestId(/^piece-/)).toHaveLength(31)
    vi.spyOn(window, 'confirm').mockReturnValue(true)
    fireEvent.click(screen.getByRole('button', { name: 'Xin thua' }))
    expect(screen.getByText('Xin thua! Đỏ thắng!')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Chơi lại' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Rời phòng' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chơi hai người cùng máy' }))
    expect(screen.getAllByTestId(/^piece-/)).toHaveLength(32)
    expect(screen.getByRole('button', { name: 'Sẵn sàng' })).toBeInTheDocument()
  })
  it('giữ nút hành động trong animation và chuyển viền báo lượt sang người chơi đen', () => {
    vi.useFakeTimers()
    window.matchMedia = vi.fn().mockImplementation(query => ({ matches: !query.includes('prefers-reduced-motion'), addEventListener() {}, removeEventListener() {} }))
    mount()
    act(() => vi.advanceTimersByTime(1000))
    fireEvent.click(screen.getByRole('button', { name: 'Sẵn sàng' }))
    act(() => vi.advanceTimersByTime(1300))
    const draw = screen.getByRole('button', { name: 'Cầu hòa' })
    const resign = screen.getByRole('button', { name: 'Xin thua' })
    expect(screen.getByTestId('avatar-red')).toHaveAttribute('data-active', 'true')
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 7, cột 1, 兵' }))
    fireEvent.click(screen.getByRole('button', { name: 'Hàng 6, cột 1' }))
    expect(draw).toBeVisible()
    expect(draw).toBeDisabled()
    expect(resign).toBeVisible()
    act(() => vi.advanceTimersByTime(400))
    expect(screen.getByRole('button', { name: 'Cầu hòa' })).toBe(draw)
    expect(draw).toBeEnabled()
    expect(resign).toBeEnabled()
    expect(screen.getByTestId('avatar-red')).toHaveAttribute('data-active', 'false')
    expect(screen.getByTestId('avatar-black')).toHaveAttribute('data-active', 'true')
  })
  it('chỉ hiện quân và người chơi khi mở xong, không tự bắt đầu ván', () => {
    vi.useFakeTimers()
    window.matchMedia = vi.fn().mockImplementation(query => ({ matches: !query.includes('prefers-reduced-motion'), addEventListener() {}, removeEventListener() {} }))
    mount()
    expect(screen.getByTestId('room-entrance')).toHaveAttribute('inert')
    expect(screen.getByTestId('piece-0-0')).not.toBeVisible()
    expect(screen.queryByRole('button', { name: 'Sẵn sàng' })).not.toBeInTheDocument()
    expect(screen.getByTestId('avatar-red')).not.toBeVisible()
    expect(screen.getByTestId('avatar-black')).not.toBeVisible()
    act(() => vi.advanceTimersByTime(599))
    expect(screen.getByTestId('piece-0-0')).not.toBeVisible()
    act(() => vi.advanceTimersByTime(1))
    expect(screen.getByTestId('room-entrance')).not.toHaveAttribute('inert')
    expect(screen.getByTestId('avatar-red')).toBeVisible()
    expect(screen.getByTestId('avatar-black')).toBeVisible()
    expect(screen.getByTestId('piece-0-0')).toBeVisible()
    expect(screen.getByRole('button', { name: 'Sẵn sàng' })).toBeEnabled()
    expect(useGameStore.getState().game.phase).toBe('ready')
  })
  it.each(['red', 'black'] as const)('hiển thị bên thắng khi %s hết giờ dù đang có thông báo khác', side => {
    vi.useFakeTimers()
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Chụp hình' }))
    act(() => {
      useGameStore.getState().start(-1300)
      const game = useGameStore.getState().game
      useGameStore.setState({ game: { ...game, currentTurn: side, remainingTime: { ...game.remainingTime, [side]: 100 } } })
      useSessionStore.setState({ notice: 'Thông báo cũ' })
      vi.advanceTimersByTime(200)
    })
    expect(screen.queryByRole('status', { name: 'Kết quả ván cờ' })).not.toBeInTheDocument()
    expect(useGameStore.getState().game.result?.winner).toBe(side === 'red' ? 'black' : 'red')
    expect(screen.getByRole('button', { name: 'Hàng 7, cột 1, 兵' })).toBeDisabled()
    expect(screen.getByRole('img', { name: 'Người thắng vui mừng' })).toBeInTheDocument()
    expect(screen.getByRole('img', { name: 'Người thua khóc' })).toBeInTheDocument()
    act(() => vi.advanceTimersByTime(2000))
    expect(screen.getByRole('button', { name: 'Sẵn sàng' })).toBeEnabled()
  })
  it('chat escape HTML, emoji, tin nhanh, vào/rời phòng và đổi tên', () => {
    mount()
    fireEvent.click(screen.getByRole('button', { name: 'Mở trò chuyện' }))
    fireEvent.change(screen.getByRole('textbox', { name: 'Nội dung chat' }), { target: { value: '<img src=x> hello' } })
    fireEvent.submit(document.getElementById('chatForm')!)
    expect(screen.getByText('<img src=x> hello')).toBeInTheDocument()
    expect(document.querySelector('img[src="x"]')).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Biểu cảm' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chèn 👍' }))
    expect(screen.getByRole('textbox', { name: 'Nội dung chat' })).toHaveValue('👍')
    fireEvent.click(screen.getByRole('button', { name: 'Gợi ý chat' }))
    fireEvent.click(screen.getByRole('button', { name: 'Nước đi hay!' }))
    expect(within(screen.getByRole('log')).getByText('Nước đi hay!')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Rời phòng' }))
    expect(screen.getByRole('main', { name: 'Màn hình chính' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Chọn Bàn' }))
    expect(screen.getByRole('main', { name: 'Chọn Bàn' })).toBeInTheDocument()
    fireEvent.change(screen.getByRole('textbox', { name: 'Tên người chơi' }), { target: { value: 'Người mới' } })
    fireEvent.click(screen.getByRole('button', { name: 'Đóng' }))
    fireEvent.click(screen.getByRole('button', { name: 'Chơi hai người cùng máy' }))
    expect(screen.getByRole('heading', { name: 'Người mới' })).toBeInTheDocument()
  })
})
