interface Props { visible: boolean; disabled: boolean; drawDisabled: boolean; takebackDisabled: boolean; takebacksLeft: number; onDraw: () => void; onResign: () => void; onTakeback: () => void }
const actionButton = 'flex min-h-[34px] cursor-pointer items-center justify-center gap-2 rounded-[3px] border border-[#a99b70] bg-[linear-gradient(#817957aa,#3d452ed9)] font-arial text-lg leading-[normal] font-bold text-[#fff5dd] not-italic [text-shadow:0_1px_2px_#192213] enabled:hover:bg-[#797746] enabled:hover:bg-none disabled:cursor-wait focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#ffe290] compact:min-h-[25px] compact:gap-[3px] compact:px-[5px] compact:py-0.5 compact:text-[11px]'
export function MatchActions({ visible, disabled, drawDisabled, takebackDisabled, takebacksLeft, onDraw, onResign, onTakeback }: Props) {
  const takebackUnavailable = takebackDisabled || takebacksLeft <= 0
  return <div className="relative mt-[25px] grid w-[150px] -translate-x-[12px] -translate-y-[18px] gap-[9px] compact:fixed compact:bottom-[3px] compact:left-16 compact:z-12 compact:m-0 compact:translate-0 compact:flex compact:w-auto compact:gap-[5px] low-desktop:gap-[5px]" id="matchActions" hidden={!visible}>
    <button className={actionButton} id="drawButton" disabled={disabled || drawDisabled} onClick={onDraw}><span className="font-serif text-2xl/none font-normal not-italic compact:text-sm" aria-hidden="true">🤝</span> Cầu hòa</button>
    <button className={actionButton} id="resignButton" disabled={disabled} onClick={onResign}><span className="font-serif text-2xl/none font-normal not-italic compact:text-sm" aria-hidden="true">⚑</span> Xin thua</button>
    <button type="button" aria-label={`Đi lại · còn ${takebacksLeft} lần`} disabled={disabled || takebackUnavailable} onClick={onTakeback} style={{ opacity: takebackUnavailable ? 0.6 : 1 }} className="absolute top-1/2 left-full ml-2 grid size-11 -translate-y-1/2 cursor-pointer place-items-center rounded-full border border-[#d4b86f] bg-[radial-gradient(circle_at_35%_28%,#8d7546,#50381f_70%)] p-0 text-[#ffe69b] shadow-[inset_0_1px_0_#fff0bb88,inset_0_-2px_3px_#29190c,0_3px_5px_#10201899] enabled:hover:brightness-110 disabled:cursor-default focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#ffe290] compact:static compact:ml-0 compact:size-[36px] compact:translate-y-0">
      <svg viewBox="0 0 32 32" aria-hidden="true" className="size-[30px]" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"><path d="M7.5 12.5V6.8m0 0h5.7M7.5 6.8l5.2 5.1" /><path d="M8.7 23.2A10 10 0 1 0 7 13.4" /><path d="M13 17h6.5M13 21h4" /></svg>
    </button>
  </div>
}
